# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=1024)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='shows/images')),
            ],
        ),
    ]
