# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='show',
            options={'ordering': ['slug']},
        ),
        migrations.AddField(
            model_name='show',
            name='feed_url',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='Podcast (RSS) Feed URL'),
        ),
        migrations.AddField(
            model_name='show',
            name='google_url',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='Google Play Podcasts Page URL'),
        ),
        migrations.AddField(
            model_name='show',
            name='itunes_url',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='Apple Podcasts/iTunes Page URL'),
        ),
        migrations.AddField(
            model_name='show',
            name='stitcher_url',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='Apple Podcasts/iTunes Page URL'),
        ),
    ]
