# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_auto_20170501_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='npr_one_url',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='NPR One URL'),
        ),
        migrations.AddField(
            model_name='show',
            name='overcast_url',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='Overcast Page URL'),
        ),
        migrations.AddField(
            model_name='show',
            name='pocket_casts_url',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='Pocket Casts Page URL'),
        ),
        migrations.AlterField(
            model_name='show',
            name='stitcher_url',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='Stitcher Page URL'),
        ),
    ]
