# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0003_auto_20170501_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('date', models.DateField()),
                ('audio_url', models.URLField(max_length=1024, verbose_name='MP3 File URL')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shows.Show')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
