# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0004_episode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name="Category 'Slug'")),
                ('name', models.CharField(max_length=1024, verbose_name='Category Display Name')),
                ('order', models.IntegerField(unique=True, verbose_name='Category Display Position on Home Screen')),
                ('display_on_home', models.BooleanField(default=True, verbose_name='Display this category on Home Screen')),
            ],
            options={
                'ordering': ['-order'],
            },
        ),
        migrations.CreateModel(
            name='ShowCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shows.Category')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shows.Show')),
            ],
            options={
                'ordering': ['-order'],
            },
        ),
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='episode',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='shows.Show'),
        ),
        migrations.AddField(
            model_name='category',
            name='shows',
            field=models.ManyToManyField(through='shows.ShowCategory', to='shows.Show'),
        ),
    ]
